apiVersion : apps/v1
kind: Deployment
metadata:
     name : nginx-deployment
spec:
  replicas: 3
  selector:
       matchLabels:
           app: hello
  template:
     metadata:
        labels:
          app: hello
     spec:
       containers:
        - name: nginxcontainer
          image: nginx:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
     app: hello
  ports:
   - name: http
     protocol: TCP
     port: 80
